TEMPLATE = lib
QT =
CONFIG -= warn_on
CONFIG += warn_off
QMAKE_CXXFLAGS += -Wno-c++0x-compat
LIBS += -licuuc -licui18n
OBJECTS_DIR = .obj
include(netflixjsc.pri)
INCLUDEPATH += generated


SOURCES += $$PWD/../Source/JavaScriptCore/interpreter/CallFrame.cpp \
           $$PWD/../Source/JavaScriptCore/interpreter/RegisterFile.cpp \
           $$PWD/../Source/JavaScriptCore/interpreter/Interpreter.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSGlobalObjectFunctions.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/PropertySlot.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSArray.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSChunk.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSNotAnObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSWrapperObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ArrayConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/InitializeThreading.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/InternalFunction.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/DateInstance.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/StructureChain.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSGlobalData.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/DateConversion.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Executable.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSString.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/DatePrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/GetterSetter.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/BooleanConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/NativeErrorConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSPropertyNameIterator.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSActivation.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/MathObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/GCActivityCallback.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/FunctionConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/RegExpObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/RegExpPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ObjectConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSStaticScopeObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/TimeoutChecker.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Lookup.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Identifier.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSONObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/NumberObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/SmallStrings.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/CallData.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/BooleanPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ErrorPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/FunctionPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/SamplingCounter.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSFunction.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSCell.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSAPIValueWrapper.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/CommonIdentifiers.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/StringObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/StringPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/StrictEvalActivation.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/StringRecursionChecker.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSGlobalObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSGlobalThis.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Options.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSLock.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ArrayPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSDateMath.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSVariableObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Arguments.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ArgList.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Error.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ErrorInstance.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSValue.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ExceptionHelpers.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Completion.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/UString.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ErrorConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/DateConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/PropertyNameArray.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/MemoryStatistics.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/PropertyDescriptor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ScopeChain.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/NativeErrorPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/NumberPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/BooleanObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ConstructData.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/ObjectPrototype.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/NumberConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/RegExpCache.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSBoundFunction.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/RegExpConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/LiteralParser.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Operations.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/Structure.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSByteArray.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/JSObject.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/RegExp.cpp \
           $$PWD/../Source/JavaScriptCore/runtime/StringConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/heap/AllocationSpace.cpp \
           $$PWD/../Source/JavaScriptCore/heap/HandleStack.cpp \
           $$PWD/../Source/JavaScriptCore/heap/HandleHeap.cpp \
           $$PWD/../Source/JavaScriptCore/heap/ConservativeRoots.cpp \
           $$PWD/../Source/JavaScriptCore/heap/BumpSpace.cpp \
           $$PWD/../Source/JavaScriptCore/heap/DFGCodeBlocks.cpp \
           $$PWD/../Source/JavaScriptCore/heap/MarkedBlock.cpp \
           $$PWD/../Source/JavaScriptCore/heap/Heap.cpp \
           $$PWD/../Source/JavaScriptCore/heap/MachineStackMarker.cpp \
           $$PWD/../Source/JavaScriptCore/heap/VTableSpectrum.cpp \
           $$PWD/../Source/JavaScriptCore/heap/MarkedSpace.cpp \
           $$PWD/../Source/JavaScriptCore/heap/MarkStack.cpp \
           $$PWD/../Source/JavaScriptCore/heap/WriteBarrierSupport.cpp \
           $$PWD/../Source/JavaScriptCore/yarr/YarrSyntaxChecker.cpp \
           $$PWD/../Source/JavaScriptCore/yarr/YarrPattern.cpp \
           $$PWD/../Source/JavaScriptCore/yarr/YarrJIT.cpp \
           $$PWD/../Source/JavaScriptCore/yarr/YarrInterpreter.cpp \
           $$PWD/../Source/JavaScriptCore/bytecompiler/BytecodeGenerator.cpp \
           $$PWD/../Source/JavaScriptCore/bytecompiler/NodesCodegen.cpp \
           $$PWD/../Source/JavaScriptCore/assembler/ARMAssembler.cpp \
           $$PWD/../Source/JavaScriptCore/assembler/MacroAssemblerARM.cpp \
           $$PWD/../Source/JavaScriptCore/assembler/MacroAssemblerSH4.cpp \
           $$PWD/../Source/JavaScriptCore/assembler/ARMv7Assembler.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSStringRef.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSValueRef.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSWeakObjectMapRefPrivate.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSClassRef.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSContextRef.cpp \
           $$PWD/../Source/JavaScriptCore/API/OpaqueJSString.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSBase.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSCallbackObject.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSCallbackFunction.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSObjectRef.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSCallbackConstructor.cpp \
           $$PWD/../Source/JavaScriptCore/API/JSProfilerPrivate.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGSpeculativeJIT32_64.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGSpeculativeJIT.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGOperations.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGJITCompiler.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGThunks.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGOSRExitCompiler.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGOSRExit.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGAbstractState.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGGraph.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGAssemblyHelpers.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGDriver.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGOSRExitCompiler32_64.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGOSRExitCompiler64.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGRepatch.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGCorrectableJumpPoint.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGCapabilities.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGPropagator.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGOSREntry.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp \
           $$PWD/../Source/JavaScriptCore/dfg/DFGSpeculativeJIT64.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/JumpTable.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/StructureStubInfo.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/DFGExitProfile.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/MethodCallLinkInfo.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/MethodCallLinkStatus.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/PutByIdStatus.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/CallLinkInfo.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/CodeBlock.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/SamplingTool.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/CallLinkStatus.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/GetByIdStatus.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/PredictedType.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/Opcode.cpp \
           $$PWD/../Source/JavaScriptCore/bytecode/ValueProfile.cpp \
           $$PWD/../Source/JavaScriptCore/profiler/Profiler.cpp \
           $$PWD/../Source/JavaScriptCore/profiler/Profile.cpp \
           $$PWD/../Source/JavaScriptCore/profiler/ProfileGenerator.cpp \
           $$PWD/../Source/JavaScriptCore/profiler/ProfileNode.cpp \
           $$PWD/../Source/JavaScriptCore/debugger/Debugger.cpp \
           $$PWD/../Source/JavaScriptCore/debugger/DebuggerCallFrame.cpp \
           $$PWD/../Source/JavaScriptCore/debugger/DebuggerActivation.cpp \
           $$PWD/../Source/JavaScriptCore/AllInOneFile.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/CurrentTime.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/NullPtr.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/StringExtras.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/DecimalNumber.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/HashTable.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ByteArray.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/SHA1.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/OSAllocatorPosix.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ThreadIdentifierDataPthreads.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/PageAllocationAligned.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ArrayBufferView.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/text/StringImpl.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/text/AtomicString.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/text/StringBuilder.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/text/StringStatics.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/text/CString.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/text/WTFString.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/Threading.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/MetaAllocator.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/FastMalloc.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/NumberOfCores.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ThreadingPthreads.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/MainThread.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/TCSystemAlloc.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/Assertions.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/DynamicAnnotations.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ThreadingNone.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/BitVector.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/MD5.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/unicode/UTF8.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/unicode/icu/CollatorICU.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/unicode/CollatorDefault.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/RandomNumber.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/OSRandomSource.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/StackBounds.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/TypeTraits.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/SizeLimits.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/RefCountedLeakCounter.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/CryptographicallyRandomNumber.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ParallelJobsGeneric.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/ArrayBuffer.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/DateMath.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/threads/BinarySemaphore.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/WTFThreadData.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/PageBlock.cpp \
           $$PWD/../Source/JavaScriptCore/parser/ParserArena.cpp \
           $$PWD/../Source/JavaScriptCore/parser/Parser.cpp \
           $$PWD/../Source/JavaScriptCore/parser/Lexer.cpp \
           $$PWD/../Source/JavaScriptCore/parser/SourceProviderCache.cpp \
           $$PWD/../Source/JavaScriptCore/parser/Nodes.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITOpcodes.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITCall32_64.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITArithmetic32_64.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JIT.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITArithmetic.cpp \
           $$PWD/../Source/JavaScriptCore/jit/ExecutableAllocatorFixedVMPool.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITCall.cpp \
           $$PWD/../Source/JavaScriptCore/jit/ExecutableAllocator.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITStubs.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITExceptions.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITOpcodes32_64.cpp \
           $$PWD/../Source/JavaScriptCore/jit/ThunkGenerators.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITPropertyAccess32_64.cpp \
           $$PWD/../Source/JavaScriptCore/jit/JITPropertyAccess.cpp \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/strtod.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/double-conversion.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/diy-fp.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/bignum.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/fast-dtoa.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/bignum-dtoa.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/fixed-dtoa.cc \
           $$PWD/../Source/JavaScriptCore/wtf/dtoa/cached-powers.cc \
 
